#mysql datasource 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restapi?useSSL=false
    username: root
    password: root
    dbcp2:
      test-while-idle: true
      validation-query: select 1
         
 #jpa properties     
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        
#Http(Tomcat) Server Port
server:
  port: 8087